type: CheckConfig
api_version: core/v2
metadata:
  name: check-cpu-better
  namespace: default
  labels:
    contacts: ops,helpdesk
spec:
  command: sensu-go-cpu-check -w 70 -c 85
  runtime_assets:
  - sensu-go-cpu-check-linux
  interval: 10
  publish: true
  output_metric_format: nagios_perfdata
  output_metric_handlers: ["influxdb"]
  check_hooks:
  - warning:
    - get_top_processes
  - critical:
    - get_top_processes
  handlers:
  - email
  subscriptions:
  - caching_servers