type: HookConfig
api_version: core/v2
metadata:
  annotations: null
  labels: null
  name: halt_gremlin_attacks
  namespace: default
spec:
  command: |-
    curl -I -X DELETE "https://api.gremlin.com/v1/attacks?teamId=$TEAMID" -H "Authorization: Bearer $GREMLIN_API_TOKEN" -H "accept: text/plain" 
  stdin: false
  timeout: 60
