---
type: EventFilter
api_version: core/v2
metadata:
  name: contact_helpdesk
  namespace: default
spec:
  action: allow
  runtime_assets:
    - sensu-go-has-contact-filter
  expressions:
    - has_contact(event, 'helpdesk')